package com.revolution;

import java.awt.HeadlessException;
import utilities.NotifyOTP;
import utilities.DBConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class ResetPassword extends javax.swing.JFrame {

	private String uname, contact, newPasswd, SQL, otp, d_otp;
	private final Connection con = DBConnect.getConnection();
    private Statement smt;
	private ResultSet rst;

	public ResetPassword() {
		initComponents();
	}
	
	public void verifyAndUpdatePassword() {
		uname = txt_uname.getText();
		contact = txt_contact.getText();
		newPasswd = String.valueOf(txt_passwd.getPassword());
		d_otp = txt_otp.getText();
		SQL = "SELECT * FROM users WHERE uname = '" + uname + "' AND contact = '" + contact + "'";

		if (!otp.equals(d_otp)) {
			JOptionPane.showMessageDialog(this, "Invalid OTP");
			txt_otp.requestFocus();
			return;
		}

		try {
			smt = con.createStatement();
			rst = smt.executeQuery(SQL);
			if (rst.next()) {
				SQL = "UPDATE users SET password = '" + newPasswd + "' WHERE uname = '" + uname + "'";
				int rst = smt.executeUpdate(SQL);
				if (rst == 1) {
					JOptionPane.showMessageDialog(this, "Password Updated");
					Login login = new Login();
					this.dispose();
					login.setVisible(true);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Password Not Updated");
			}
		} catch (SQLException | HeadlessException e) {
			System.err.println(e);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_otp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_uname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_passwd = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Revolution Library - Password Reset");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_otp.setBackground(new java.awt.Color(0, 128, 128));
        txt_otp.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_otp.setForeground(new java.awt.Color(255, 255, 255));
        txt_otp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otp1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 360, -1));

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("OTP");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 360, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/question-60.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 60, 60));

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RESET PASSWORD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 230, -1));

        txt_uname.setBackground(new java.awt.Color(0, 128, 128));
        txt_uname.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_uname.setForeground(new java.awt.Color(255, 255, 255));
        txt_uname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_unameFocusLost(evt);
            }
        });
        jPanel1.add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 360, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/user_60.png"))); // NOI18N
        jLabel14.setText("jLabel13");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 60, 60));

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 360, -1));

        txt_contact.setBackground(new java.awt.Color(0, 128, 128));
        txt_contact.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 250, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/contact_60.png"))); // NOI18N
        jLabel16.setText("jLabel13");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 60, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/password_60.png"))); // NOI18N
        jLabel15.setText("jLabel13");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 60, 60));

        txt_passwd.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jPanel1.add(txt_passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 370, -1));

        jLabel17.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("New Password");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 360, -1));

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 360, -1));

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, 480, 50));

        jButton3.setBackground(new java.awt.Color(255, 51, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/back_16.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, -1));

        jCheckBox1.setFont(new java.awt.Font("Cantarell", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 200, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Send OTP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 310, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unameFocusLost

    }//GEN-LAST:event_txt_unameFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		Login login = new Login();
		login.setVisible(true);
		dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
		if (jCheckBox1.isSelected()) {
			txt_passwd.setEchoChar((char) 0);
		} else {
			txt_passwd.setEchoChar('*');
		}
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		uname = txt_uname.getText();
		newPasswd = String.valueOf(txt_passwd.getPassword());

		if (uname.equals("")) {
			JOptionPane.showMessageDialog(null, "Please enter an username");
			return;
		}

		if (newPasswd.equals("")) {
			JOptionPane.showMessageDialog(null, "New Password Can't Be Empty");
			return;
		}
		verifyAndUpdatePassword();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		SQL = "SELECT uname, contact FROM users WHERE uname = '" + txt_uname.getText() + "'";
		try {
			smt = con.createStatement();
			rst = smt.executeQuery(SQL);
			if(rst.next()) {
				if(rst.getString("contact").equals(txt_contact.getText())) {
					otp = new NotifyOTP().generateOTP(txt_contact.getText());
				} else {
					JOptionPane.showMessageDialog(this, "Please enter correct contact");
					txt_contact.requestFocus();
				}
			} else {
				JOptionPane.showMessageDialog(this, "Username not found", "Error", 2);
				txt_uname.requestFocus();
			}
		} catch(SQLException e) {
			System.err.print(e);
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_otp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otp1ActionPerformed

    }//GEN-LAST:event_txt_otp1ActionPerformed

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		java.awt.EventQueue.invokeLater(() -> {
			new ResetPassword().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_otp;
    private javax.swing.JPasswordField txt_passwd;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
