package com.revolution;

import utilities.DBConnect;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.concurrent.TimeUnit;

public class ReturnBook extends javax.swing.JFrame {

	private final String dots = "...............................................................................";
	private String bookId, memberId, SQL;
	private final Connection con = DBConnect.getConnection();
    private Statement smt;
	private ResultSet rs;
	private PreparedStatement pst;
	private Date today, duedate;

	public ReturnBook() {
		initComponents();
	}

	public void getIssueBookDetails() {
		bookId = txt_bookId.getText();
		memberId = txt_memberId.getText();
		SQL = "SELECT * FROM issue_book_details WHERE book_id = '" + bookId + "' AND member_id = '" + memberId + "' AND status = 'pending'";

		try {

			pst = con.prepareStatement(SQL);
			rs = pst.executeQuery();
			if (rs.next()) {
				lbl_issueId.setText(rs.getString("id"));
				lbl_bookName.setText(rs.getString("book_name"));
				lbl_memberName.setText(rs.getString("member_name"));
				lbl_issueDate.setText(rs.getString("issue_date"));
				lbl_dueDate.setText(rs.getString("due_date"));
				jPanel1.setBackground(new Color(0, 51, 153));
				lbl_error.setText("RECORD FOUND");
				fineDefaulters();
			} else {
				lbl_issueId.setText(dots);
				lbl_bookName.setText(dots);
				lbl_memberName.setText(dots);
				lbl_issueDate.setText(dots);
				lbl_dueDate.setText(dots);
				jPanel1.setBackground(Color.RED);
				lbl_error.setText("NO RECORD FOUND");

			}
		} catch (SQLException e) {
			System.err.println(e);
		}
	}

	public void fineDefaulters() {
		today = new Date();
		bookId = txt_bookId.getText();
		memberId = txt_memberId.getText();
		SQL = "SELECT * FROM issue_book_details WHERE due_date < '" + today
				+ "' AND book_id = " + bookId + " AND member_id = " + memberId + " AND status = 'pending'";
		try {
			smt = con.createStatement();
			rs = smt.executeQuery(SQL);
			if (rs.next()) {
				duedate = rs.getDate("due_date");
				if (duedate.compareTo(today) < 0) {
					long diff = today.getTime() - duedate.getTime();
					long late = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
					jPanel1.setBackground(Color.RED);
					lbl_error.setText("PENALTY : " + late + " DAYS LATE || LATE FINE : Rs." + late * 5 + "/-");
				}
			}
		} catch (SQLException e) {
			System.err.println(e);
		}
	}

	public boolean returnBook() {
		boolean isReturned = true;
		bookId = txt_bookId.getText();
		memberId = txt_memberId.getText();
		SQL = "UPDATE issue_book_details SET STATUS = 'returned' WHERE book_id = " + bookId + " AND member_id = " + memberId + " AND status = 'pending'";

		try {
			pst = con.prepareStatement(SQL);
			int rowCount = pst.executeUpdate();
			if (rowCount <= 0) {
				isReturned = false;
			}
		} catch (SQLException e) {
			System.err.println(e);
		}
		return isReturned;
	}

	public void updateBookCount() {
		bookId = txt_bookId.getText();
		try {
			SQL = "UPDATE book_details SET quantity = quantity + 1 WHERE book_id = " + bookId + "";
			pst = con.prepareStatement(SQL);
			int rowCount = pst.executeUpdate();
			if (rowCount > 0) {
				JOptionPane.showMessageDialog(this, "BOOK COUNT UPDATED");
			} else {
				JOptionPane.showMessageDialog(this, "CAN'T UPDATE BOOK COUNT");
			}
		} catch (HeadlessException | SQLException e) {
			System.err.println(e);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_bookId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_memberId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_issueId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_memberName = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        lbl_dueDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_error = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Revolution Library - Issued Bood Details");
        setName("returnbook"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/back_16.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 10, 40, -1));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_other/return-black-60.png"))); // NOI18N
        jLabel2.setText("Return Book");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 130, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 190, 410, -1));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel3.setText("Book ID           :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, -1, -1));

        txt_bookId.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_bookId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 370, 360, -1));

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel4.setText("Member ID     :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, -1, -1));

        txt_memberId.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_memberId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_memberId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 430, 360, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 610, 340, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Return Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 680, 340, 50));

        jPanel5.setBackground(new java.awt.Color(0, 128, 128));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due Date");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, 60));

        jLabel6.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(":");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, 60));

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book Name");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, 60));

        jLabel8.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Member Name");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, 60));

        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Issue Date");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, 60));

        jLabel11.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 60));

        jLabel12.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 60));

        jLabel13.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, 60));

        jLabel14.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, 60));

        jLabel15.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Issue ID");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 50));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/book-60.png"))); // NOI18N
        jLabel1.setText("Issued Book Details");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 128, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 360, 20));

        lbl_issueId.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_issueId.setForeground(new java.awt.Color(255, 255, 255));
        lbl_issueId.setText("...............................................................................");
        jPanel5.add(lbl_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 400, 50));

        lbl_bookName.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bookName.setText("...............................................................................");
        jPanel5.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 400, 50));

        lbl_memberName.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_memberName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_memberName.setText("...............................................................................");
        jPanel5.add(lbl_memberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 400, 50));

        lbl_issueDate.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_issueDate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_issueDate.setText("...............................................................................");
        jPanel5.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 400, 50));

        lbl_dueDate.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        lbl_dueDate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dueDate.setText("...............................................................................");
        jPanel5.add(lbl_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 400, 50));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_error.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lbl_error.setForeground(new java.awt.Color(255, 255, 255));
        lbl_error.setText("REVOLUTION LIBRARY");
        jPanel1.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 620, 40));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 800, 640, 40));

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("STATUS :");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 760, 130, 40));

        jLabel16.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Due Date");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, 60));

        jLabel17.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(":");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 855));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 876));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		HomePage home = new HomePage();
		home.setVisible(true);
		dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		if (txt_bookId.getText().equals("") || txt_memberId.getText().equals("")) {
			jPanel1.setBackground(Color.RED);
			lbl_error.setText("ENTER REQUIRED DATA");
		} else {
			if (txt_bookId.getText().matches("[0-9]*") && txt_memberId.getText().matches("[0-9]*")) {
				getIssueBookDetails();
			} else {
				jPanel1.setBackground(Color.RED);
				lbl_error.setText("ENTER VALID DATE");
			}
		}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		if (txt_bookId.getText().equals("") || txt_memberId.getText().equals("")) {
			lbl_error.setText("ENTER REQUIRED DATA");
		} else {
			getIssueBookDetails();
			if (returnBook() == true) {
				updateBookCount();
				lbl_error.setText("BOOK RETURNED");
				new utilities.NotifyReturn().notifyReturn(lbl_issueId.getText());
			} else {
				lbl_error.setText("BOOK RETURN FAILED");
			}
		}
    }//GEN-LAST:event_jButton4ActionPerformed

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		java.awt.EventQueue.invokeLater(() -> {
			new ReturnBook().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_dueDate;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JLabel lbl_issueId;
    private javax.swing.JLabel lbl_memberName;
    private javax.swing.JTextField txt_bookId;
    private javax.swing.JTextField txt_memberId;
    // End of variables declaration//GEN-END:variables
}
