package com.revolution;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import utilities.NotifyOTP;

public class Signup extends javax.swing.JFrame {

	private String userName, passWord, email, contact, SQL, otp, d_otp;
	private final Connection con = utilities.DBConnect.getConnection();
	private Statement smt;
	private PreparedStatement pst;
	private ResultSet rst;

	public Signup() {
		initComponents();
		txt_uname.requestFocus();
	}
	
	public void insertSignupDetails() {
		userName = txt_uname.getText();
		passWord = String.valueOf(txt_passwd.getPassword());
		email = txt_email.getText();
		contact = txt_contact.getText();
		d_otp = txt_otp.getText();

		if (!otp.equals(d_otp)) {
			JOptionPane.showMessageDialog(this, "Invalid OTP");
			txt_otp.requestFocus();
			return;
		}
		SQL = "INSERT INTO users(uname,password,email,contact) VALUES('" + userName + "','" + passWord + "','" + email + "','" + contact + "')";
		try {
			smt = con.createStatement();
			int rows = smt.executeUpdate(SQL);
			if (rows == 1) {
				this.dispose();
				Login lgn = new Login();
				lgn.setVisible(true);
				JOptionPane.showMessageDialog(this, "Account created successfully");
			}
		} catch (HeadlessException | SQLException e) {
			JOptionPane.showMessageDialog(this, e);
		}

	}
	
	public boolean validateSignUp() {
		email = txt_email.getText();

		if (txt_uname.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Please enter username");
			txt_uname.requestFocus();
			return false;
		}
		if (String.valueOf(txt_passwd.getPassword()).equals("")) {
			JOptionPane.showMessageDialog(this, "Please enter password");
			txt_passwd.requestFocus();
			return false;
		}
		if (email.equals("") || !email.matches("^.+@\\S+$")) {
			JOptionPane.showMessageDialog(this, "Please enter valid email");
			txt_email.requestFocus();
			return false;
		}
		if (!txt_contact.getText().matches("[6789]{1}[0-9]{9}")) {
			JOptionPane.showMessageDialog(this, "Please enter valid contact number");
			txt_otp.requestFocus();
			return false;
		}
		if (txt_otp.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Please enter OTP");
			return false;
		}
		return true;
	}
	
	public boolean checkDublicateUser() {
		boolean isExist = false;
		userName = txt_uname.getText();
		SQL = "SELECT * from users where uname = '" + userName + "'";
		try {
			pst = con.prepareStatement(SQL);
			rst = pst.executeQuery();
			if (rst.next()) {
				isExist = true;
			}
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(this, e);
		}
		return isExist;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_uname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_otp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        txt_passwd = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Revolution Library - Signup");
        setName("signup"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Revolution Library");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 390, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Welcome To");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 290, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup-library-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 870, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 830));

        jPanel2.setBackground(new java.awt.Color(0, 128, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton2.setText("SIGNUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 470, 40));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Signup Page");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(224, 224, 224));
        jLabel5.setText("Create New Account Here");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 360, -1));

        txt_uname.setBackground(new java.awt.Color(0, 128, 128));
        txt_uname.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_uname.setForeground(new java.awt.Color(255, 255, 255));
        txt_uname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_unameFocusLost(evt);
            }
        });
        jPanel2.add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 360, -1));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOGIN");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, 280, 40));

        jButton4.setBackground(new java.awt.Color(255, 51, 102));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SIGNUP");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 280, 40));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Signup Page");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(224, 224, 224));
        jLabel8.setText("Create New Account Here");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 340, -1));

        jTextField3.setBackground(new java.awt.Color(51, 153, 255));
        jTextField3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 51, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 340, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 510, 830));

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 360, -1));

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 360, -1));

        txt_email.setBackground(new java.awt.Color(0, 128, 128));
        txt_email.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 360, -1));

        txt_otp.setBackground(new java.awt.Color(0, 128, 128));
        txt_otp.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_otp.setForeground(new java.awt.Color(255, 255, 255));
        txt_otp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(txt_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 360, -1));

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("OPT");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 360, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/question-60.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 60, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/user_60.png"))); // NOI18N
        jLabel14.setText("jLabel13");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/password_60.png"))); // NOI18N
        jLabel15.setText("jLabel13");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 60));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/email_60.png"))); // NOI18N
        jLabel16.setText("jLabel13");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 60, 60));

        jLabel17.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Contact");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 360, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_light/contact_60.png"))); // NOI18N
        jLabel18.setText("jLabel13");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 60, 60));

        txt_contact.setBackground(new java.awt.Color(0, 128, 128));
        txt_contact.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 240, -1));

        txt_passwd.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        jPanel2.add(txt_passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 360, -1));

        jCheckBox1.setFont(new java.awt.Font("Cantarell", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 200, -1));

        jLabel19.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Already have an account, click here to login.");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 320, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Send OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 510, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		if (validateSignUp() == true) {
			if (checkDublicateUser() == false) {
				insertSignupDetails();
			} else {
				JOptionPane.showMessageDialog(this, "User already exist");
				txt_passwd.requestFocus();
			}
		}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unameFocusLost
		if (checkDublicateUser() == true) {
			JOptionPane.showMessageDialog(this, "Username already exist");
			txt_uname.requestFocus();
		}
    }//GEN-LAST:event_txt_unameFocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
		if (jCheckBox1.isSelected()) {
			txt_passwd.setEchoChar((char) 0);
		} else {
			txt_passwd.setEchoChar('*');
		}
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
		Login lgn = new Login();
		this.dispose();
		lgn.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		otp = new NotifyOTP().generateOTP(txt_contact.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		java.awt.EventQueue.invokeLater(() -> {
			new Signup().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_otp;
    private javax.swing.JPasswordField txt_passwd;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
